apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: tejaskawde/ruby:v1  # Replace with your application image
        ports:
        - containerPort: 3000  # Adjust according to your application's port
        env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: tejas
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_HOST
          value: postgres  # The name of the headless service created for PostgreSQL StatefulSet
        - name: POSTGRES_PORT
          value: "5432"

