apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  repository.credentials: |
    - url: https://github.com/Nutriagg/devops-assignment.git
      usernameSecret:
        name: github-credentials
        key: username
      passwordSecret:
        name: github-credentials
        key: password
  repositories: |
    - url: https://github.com/Nutriagg/devops-assignment.git
      type: git

