apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Nutriagg/devops-assignment.git
  username: Nutriagg
  password: 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
