apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/tejaskawde/test-makerble.git
  username: tejaskawde
  password: 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 

