apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: shubham554/ruby-app:v3  # Replace with your application image
        ports:
        - containerPort: 3000  # Adjust according to your application's port
        env:
        - name: RAILS_ENV
          value: production
        - name: POSTGRES_DB
          value: mydatabase
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: password
        - name: RAILS_MASTER_KEY
          value: 85532d93d03b27210354e112c92e9871
        - name: POSTGRES_HOST
          value: postgres-svc

        imagePullPolicy: Always
